"""Health Monitor for Cloud Agent.

Monitors process health, API connectivity, and system resources.
Writes status to Health/status.md and logs incidents.
"""

import json
import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Thresholds
CPU_WARNING = 70
CPU_CRITICAL = 90
MEMORY_WARNING = 80
MEMORY_CRITICAL = 95
DISK_WARNING = 85
DISK_CRITICAL = 95


class HealthMonitor:
    """Monitors cloud agent health and writes status to vault."""

    def __init__(self, vault_path: str, agent_id: str = "cloud"):
        self.vault_path = Path(vault_path)
        self.health_path = self.vault_path / "Health"
        self.logs_path = self.vault_path / "Logs"
        self.agent_id = agent_id
        self._incidents: list[dict[str, Any]] = []
        self._failure_counts: dict[str, int] = {}

        self.health_path.mkdir(parents=True, exist_ok=True)
        self.logs_path.mkdir(parents=True, exist_ok=True)

    def check_resources(self) -> dict[str, float]:
        """Check system resource usage.

        Returns:
            Dict with cpu_percent, memory_percent, disk_percent
        """
        try:
            import psutil
            cpu = psutil.cpu_percent(interval=1)
            memory = psutil.virtual_memory().percent
            disk = psutil.disk_usage("/").percent
        except (ImportError, OSError):
            # Fallback if psutil not available or path issue on Windows
            try:
                disk_usage = shutil.disk_usage(".")
                disk = (disk_usage.used / disk_usage.total) * 100
            except OSError:
                disk = 0.0
            cpu = 0.0
            memory = 0.0
            logger.warning("psutil not available, CPU/memory metrics unavailable")

        return {
            "cpu_percent": round(cpu, 1),
            "memory_percent": round(memory, 1),
            "disk_percent": round(disk, 1),
        }

    def evaluate_status(self, resources: dict[str, float]) -> str:
        """Evaluate overall status from resource metrics.

        Args:
            resources: Dict with cpu_percent, memory_percent, disk_percent

        Returns:
            Status string: "healthy", "warning", or "critical"
        """
        cpu = resources.get("cpu_percent", 0)
        memory = resources.get("memory_percent", 0)
        disk = resources.get("disk_percent", 0)

        if cpu >= CPU_CRITICAL or memory >= MEMORY_CRITICAL or disk >= DISK_CRITICAL:
            return "critical"
        if cpu >= CPU_WARNING or memory >= MEMORY_WARNING or disk >= DISK_WARNING:
            return "warning"
        return "healthy"

    def write_status(self) -> None:
        """Write current health status to Health/status.md."""
        resources = self.check_resources()
        status = self.evaluate_status(resources)
        now = datetime.now()

        recent_incidents = self._incidents[-10:] if self._incidents else []
        if recent_incidents:
            incidents_md = "\n".join(
                f"- [{i['severity']}] {i['process']}: {i['message']} ({i['timestamp']})"
                for i in recent_incidents
            )
        else:
            incidents_md = "No incidents recorded."

        content = f"""---
type: health_status
agent_id: {self.agent_id}
last_check: {now.isoformat()}
overall_status: {status}
check_interval: 60
---

# Cloud Agent Health Status

> Last Check: {now.strftime('%Y-%m-%d %H:%M:%S')}

## Overall Status: {status.title()}

## Resources

| Metric | Current | Warning | Critical |
|--------|---------|---------|----------|
| CPU | {resources['cpu_percent']}% | {CPU_WARNING}% | {CPU_CRITICAL}% |
| Memory | {resources['memory_percent']}% | {MEMORY_WARNING}% | {MEMORY_CRITICAL}% |
| Disk | {resources['disk_percent']}% | {DISK_WARNING}% | {DISK_CRITICAL}% |

## Recent Incidents

{incidents_md}

## Uptime

- Agent: {self.agent_id}
- Last check: {now.isoformat()}

---
*Auto-generated by Health Monitor*
"""
        status_file = self.health_path / "status.md"
        status_file.write_text(content, encoding="utf-8")

    def log_incident(
        self,
        process: str,
        message: str,
        severity: str = "warning",
    ) -> None:
        """Log a health incident.

        Args:
            process: Process name that had the issue
            message: Description of the incident
            severity: warning, critical, or info
        """
        incident = {
            "timestamp": datetime.now().isoformat(),
            "process": process,
            "message": message,
            "severity": severity,
        }
        self._incidents.append(incident)

        self._failure_counts[process] = self._failure_counts.get(process, 0) + 1

        self._log_action("incident", incident)

    def get_consecutive_failures(self, process: str) -> int:
        """Get count of consecutive failures for a process."""
        return self._failure_counts.get(process, 0)

    def attempt_restart(
        self,
        process_name: str,
        dry_run: bool = False,
    ) -> dict[str, Any]:
        """Attempt to restart a failed process.

        Args:
            process_name: Name of the PM2 process to restart
            dry_run: If True, don't actually restart

        Returns:
            Dict with attempted, success, dry_run
        """
        self.log_incident(
            process=process_name,
            message=f"Restart {'requested (dry-run)' if dry_run else 'attempted'}",
            severity="warning",
        )

        if dry_run:
            return {
                "attempted": True,
                "success": True,
                "dry_run": True,
                "process": process_name,
            }

        import subprocess
        try:
            result = subprocess.run(
                ["pm2", "restart", process_name],
                capture_output=True,
                text=True,
                timeout=30,
            )
            success = result.returncode == 0
            if success:
                self._failure_counts[process_name] = 0
            return {
                "attempted": True,
                "success": success,
                "dry_run": False,
                "process": process_name,
                "output": result.stdout,
            }
        except Exception as e:
            return {
                "attempted": True,
                "success": False,
                "dry_run": False,
                "process": process_name,
                "error": str(e),
            }

    def _log_action(self, action: str, details: dict[str, Any]) -> None:
        """Log action to daily log file."""
        today = datetime.now().strftime("%Y-%m-%d")
        log_file = self.logs_path / f"{today}.jsonl"

        entry = {
            "timestamp": datetime.now().isoformat(),
            "component": "health_monitor",
            "action": action,
            "details": details,
        }

        with open(log_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
