"""
Tests for BaseWatcher

Auto-generated by test-generator skill on 2026-01-19.
Run: pytest tests/test_base_watcher.py -v
"""

import pytest
from pathlib import Path
from datetime import datetime
from unittest.mock import Mock, patch
import json

from src.watchers.base_watcher import BaseWatcher


# =============================================================================
# Concrete Implementation for Testing
# =============================================================================

class ConcreteWatcher(BaseWatcher):
    """Concrete implementation of BaseWatcher for testing."""

    def __init__(self, vault_path: str, **kwargs):
        super().__init__(vault_path, **kwargs)
        self.mock_items = []

    def check_for_updates(self):
        """Return mock items for testing."""
        return self.mock_items

    def create_action_file(self, item):
        """Create a simple action file for testing."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"TEST_{timestamp}_{item}.md"
        filepath = self.needs_action / filename
        filepath.write_text(f"# Test Action: {item}\n")
        return filepath


# =============================================================================
# Tests: Initialization
# =============================================================================

class TestBaseWatcherInit:
    """Tests for BaseWatcher initialization."""

    def test_init_sets_vault_path(self, temp_vault):
        """Should set vault_path as Path object."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.vault_path == temp_vault

    def test_init_sets_needs_action_path(self, temp_vault):
        """Should set needs_action path correctly."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.needs_action == temp_vault / "Needs_Action"

    def test_init_sets_logs_path(self, temp_vault):
        """Should set logs_path correctly."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.logs_path == temp_vault / "Logs"

    def test_init_sets_inbox_path(self, temp_vault):
        """Should set inbox_path correctly."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.inbox_path == temp_vault / "Inbox"

    def test_init_default_check_interval(self, temp_vault):
        """Default check interval should be 60 seconds."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.check_interval == 60

    def test_init_custom_check_interval(self, temp_vault):
        """Should accept custom check interval."""
        watcher = ConcreteWatcher(str(temp_vault), check_interval=30)

        assert watcher.check_interval == 30

    def test_init_default_watcher_name(self, temp_vault):
        """Default watcher name should be BaseWatcher."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.watcher_name == "BaseWatcher"

    def test_init_custom_watcher_name(self, temp_vault):
        """Should accept custom watcher name."""
        watcher = ConcreteWatcher(str(temp_vault), watcher_name="CustomWatcher")

        assert watcher.watcher_name == "CustomWatcher"

    def test_init_is_running_false(self, temp_vault):
        """is_running should start as False."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher.is_running is False

    def test_init_error_count_zero(self, temp_vault):
        """Error count should start at zero."""
        watcher = ConcreteWatcher(str(temp_vault))

        assert watcher._error_count == 0

    def test_init_creates_needs_action_dir(self, tmp_path):
        """Should create Needs_Action directory if missing."""
        vault = tmp_path / "new_vault"
        vault.mkdir()

        watcher = ConcreteWatcher(str(vault))

        assert (vault / "Needs_Action").exists()

    def test_init_creates_logs_dir(self, tmp_path):
        """Should create Logs directory if missing."""
        vault = tmp_path / "new_vault"
        vault.mkdir()

        watcher = ConcreteWatcher(str(vault))

        assert (vault / "Logs").exists()

    def test_init_creates_inbox_dir(self, tmp_path):
        """Should create Inbox directory if missing."""
        vault = tmp_path / "new_vault"
        vault.mkdir()

        watcher = ConcreteWatcher(str(vault))

        assert (vault / "Inbox").exists()


# =============================================================================
# Tests: log_action
# =============================================================================

class TestLogAction:
    """Tests for log_action method."""

    def test_creates_log_file(self, temp_vault):
        """Should create daily log file."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {'data': 'value'})

        log_file = temp_vault / "Logs" / f"{today}.json"
        assert log_file.exists()

    def test_log_is_valid_json(self, temp_vault):
        """Log file should contain valid JSON."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert isinstance(logs, list)

    def test_log_entry_has_timestamp(self, temp_vault):
        """Log entry should have ISO timestamp."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert 'timestamp' in logs[0]
        # Verify it's ISO format
        datetime.fromisoformat(logs[0]['timestamp'])

    def test_log_entry_has_watcher_name(self, temp_vault):
        """Log entry should have watcher name."""
        watcher = ConcreteWatcher(str(temp_vault), watcher_name="TestWatcher")
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['watcher'] == 'TestWatcher'

    def test_log_entry_has_action_type(self, temp_vault):
        """Log entry should have action_type."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('my_action', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['action_type'] == 'my_action'

    def test_log_entry_has_details(self, temp_vault):
        """Log entry should have details dict."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {'key': 'value', 'num': 42})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['details'] == {'key': 'value', 'num': 42}

    def test_appends_to_existing_log(self, temp_vault, mock_log_file):
        """Should append to existing log file."""
        watcher = ConcreteWatcher(str(temp_vault))

        watcher.log_action('new_action', {})

        logs = json.loads(mock_log_file.read_text())
        assert len(logs) == 2

    def test_handles_corrupted_log_file(self, temp_vault):
        """Should handle corrupted log file gracefully."""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = temp_vault / "Logs" / f"{today}.json"
        log_file.write_text("not valid json {{{")

        watcher = ConcreteWatcher(str(temp_vault))
        watcher.log_action('test', {})

        # Should have created new valid log
        logs = json.loads(log_file.read_text())
        assert len(logs) == 1


# =============================================================================
# Tests: log_heartbeat
# =============================================================================

class TestLogHeartbeat:
    """Tests for log_heartbeat method."""

    def test_logs_heartbeat_action(self, temp_vault):
        """Should log heartbeat action type."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_heartbeat()

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['action_type'] == 'heartbeat'

    def test_heartbeat_includes_status(self, temp_vault):
        """Heartbeat should include status."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_heartbeat()

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['details']['status'] == 'alive'

    def test_heartbeat_includes_error_count(self, temp_vault):
        """Heartbeat should include error count."""
        watcher = ConcreteWatcher(str(temp_vault))
        watcher._error_count = 3
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_heartbeat()

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['details']['error_count'] == 3


# =============================================================================
# Tests: stop
# =============================================================================

class TestStop:
    """Tests for stop method."""

    def test_sets_is_running_false(self, temp_vault):
        """Should set is_running to False."""
        watcher = ConcreteWatcher(str(temp_vault))
        watcher.is_running = True

        watcher.stop()

        assert watcher.is_running is False

    def test_logs_stop_action(self, temp_vault):
        """Should log watcher_stopped action."""
        watcher = ConcreteWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.stop()

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['action_type'] == 'watcher_stopped'
        assert logs[0]['details']['reason'] == 'manual_stop'


# =============================================================================
# Tests: get_status
# =============================================================================

class TestGetStatus:
    """Tests for get_status method."""

    def test_returns_dict(self, temp_vault):
        """Should return a dictionary."""
        watcher = ConcreteWatcher(str(temp_vault))

        status = watcher.get_status()

        assert isinstance(status, dict)

    def test_includes_name(self, temp_vault):
        """Status should include watcher name."""
        watcher = ConcreteWatcher(str(temp_vault), watcher_name="TestWatcher")

        status = watcher.get_status()

        assert status['name'] == 'TestWatcher'

    def test_includes_is_running(self, temp_vault):
        """Status should include is_running."""
        watcher = ConcreteWatcher(str(temp_vault))
        watcher.is_running = True

        status = watcher.get_status()

        assert status['is_running'] is True

    def test_includes_error_count(self, temp_vault):
        """Status should include error count."""
        watcher = ConcreteWatcher(str(temp_vault))
        watcher._error_count = 5

        status = watcher.get_status()

        assert status['error_count'] == 5

    def test_includes_check_interval(self, temp_vault):
        """Status should include check interval."""
        watcher = ConcreteWatcher(str(temp_vault), check_interval=120)

        status = watcher.get_status()

        assert status['check_interval'] == 120

    def test_includes_vault_path(self, temp_vault):
        """Status should include vault path."""
        watcher = ConcreteWatcher(str(temp_vault))

        status = watcher.get_status()

        assert status['vault_path'] == str(temp_vault)


# =============================================================================
# Run Tests
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
