"""
Tests for FileSystemWatcher

Auto-generated by test-generator skill on 2026-01-19.
Run: pytest tests/test_filesystem_watcher.py -v
Run with coverage: pytest tests/test_filesystem_watcher.py --cov=src/watchers
"""

import pytest
from pathlib import Path
from datetime import datetime
from unittest.mock import Mock, patch, MagicMock
import json
import time

from src.watchers.filesystem_watcher import FileSystemWatcher, DropFolderHandler
from src.watchers.base_watcher import BaseWatcher


# =============================================================================
# Tests: FileSystemWatcher Initialization
# =============================================================================

class TestFileSystemWatcherInit:
    """Tests for FileSystemWatcher initialization."""

    def test_init_creates_watch_folder(self, temp_vault):
        """Initialization should create the watch folder if it doesn't exist."""
        watch_folder = temp_vault / "CustomDrop"
        assert not watch_folder.exists()

        watcher = FileSystemWatcher(str(temp_vault), str(watch_folder))

        assert watch_folder.exists()

    def test_init_creates_needs_action_folder(self, temp_vault):
        """Initialization should ensure Needs_Action folder exists."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert (temp_vault / "Needs_Action").exists()

    def test_init_creates_logs_folder(self, temp_vault):
        """Initialization should ensure Logs folder exists."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert (temp_vault / "Logs").exists()

    def test_init_creates_inbox_folder(self, temp_vault):
        """Initialization should ensure Inbox folder exists."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert (temp_vault / "Inbox").exists()

    def test_init_defaults_watch_folder_to_drop(self, temp_vault):
        """Default watch folder should be vault/Drop."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert watcher.watch_folder == temp_vault / "Drop"

    def test_init_sets_watcher_name(self, temp_vault):
        """Watcher name should be FileSystemWatcher."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert watcher.watcher_name == "FileSystemWatcher"

    def test_init_processed_files_empty(self, temp_vault):
        """Processed files set should start empty."""
        watcher = FileSystemWatcher(str(temp_vault))

        assert len(watcher.processed_files) == 0


# =============================================================================
# Tests: check_for_updates
# =============================================================================

class TestCheckForUpdates:
    """Tests for check_for_updates method."""

    def test_returns_empty_list_when_no_files(self, temp_vault):
        """Should return empty list when drop folder is empty."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.check_for_updates()

        assert result == []

    def test_finds_new_text_file(self, temp_vault, sample_text_file):
        """Should find new text file in drop folder."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.check_for_updates()

        assert len(result) == 1
        assert result[0].name == "sample.txt"

    def test_finds_multiple_files(self, temp_vault, multiple_files):
        """Should find all new files in drop folder."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.check_for_updates()

        assert len(result) == 4

    def test_ignores_hidden_files(self, temp_vault, temp_drop_folder):
        """Should ignore files starting with dot."""
        hidden_file = temp_drop_folder / ".hidden"
        hidden_file.write_text("hidden content")

        watcher = FileSystemWatcher(str(temp_vault))
        result = watcher.check_for_updates()

        assert len(result) == 0

    def test_ignores_temp_files(self, temp_vault, temp_drop_folder):
        """Should ignore files starting with tilde."""
        temp_file = temp_drop_folder / "~tempfile.tmp"
        temp_file.write_text("temp content")

        watcher = FileSystemWatcher(str(temp_vault))
        result = watcher.check_for_updates()

        assert len(result) == 0

    def test_ignores_already_processed_files(self, temp_vault, sample_text_file):
        """Should not return files already in processed_files set."""
        watcher = FileSystemWatcher(str(temp_vault))
        watcher.processed_files.add("sample.txt")

        result = watcher.check_for_updates()

        assert len(result) == 0


# =============================================================================
# Tests: create_action_file
# =============================================================================

class TestCreateActionFile:
    """Tests for create_action_file method."""

    def test_creates_markdown_file(self, temp_vault, sample_text_file):
        """Should create a .md file in Needs_Action."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)

        assert result.exists()
        assert result.suffix == ".md"

    def test_creates_file_in_needs_action(self, temp_vault, sample_text_file):
        """Action file should be in Needs_Action folder."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)

        assert result.parent == temp_vault / "Needs_Action"

    def test_filename_starts_with_file(self, temp_vault, sample_text_file):
        """Action filename should start with FILE_."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)

        assert result.name.startswith("FILE_")

    def test_copies_file_to_inbox(self, temp_vault, sample_text_file):
        """Original file should be copied to Inbox."""
        watcher = FileSystemWatcher(str(temp_vault))

        watcher.create_action_file(sample_text_file)

        inbox_file = temp_vault / "Inbox" / "sample.txt"
        assert inbox_file.exists()

    def test_marks_file_as_processed(self, temp_vault, sample_text_file):
        """File should be added to processed_files set."""
        watcher = FileSystemWatcher(str(temp_vault))

        watcher.create_action_file(sample_text_file)

        assert "sample.txt" in watcher.processed_files

    def test_action_file_contains_frontmatter(self, temp_vault, sample_text_file):
        """Action file should contain YAML frontmatter."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)
        content = result.read_text()

        assert content.startswith("---")
        assert "type: file_drop" in content
        assert "status: pending" in content

    def test_action_file_contains_filename(self, temp_vault, sample_text_file):
        """Action file should reference original filename."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)
        content = result.read_text()

        assert "sample.txt" in content

    def test_action_file_contains_size(self, temp_vault, sample_text_file):
        """Action file should contain file size."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher.create_action_file(sample_text_file)
        content = result.read_text()

        assert "Size" in content


# =============================================================================
# Tests: Priority Determination
# =============================================================================

class TestDeterminePriority:
    """Tests for _determine_priority method."""

    def test_pdf_is_high_priority(self, temp_vault, sample_pdf_file):
        """PDF files should be high priority."""
        watcher = FileSystemWatcher(str(temp_vault))

        priority = watcher._determine_priority(sample_pdf_file)

        assert priority == "high"

    def test_docx_is_high_priority(self, temp_vault, temp_drop_folder):
        """DOCX files should be high priority."""
        docx_file = temp_drop_folder / "document.docx"
        docx_file.write_bytes(b"fake docx")

        watcher = FileSystemWatcher(str(temp_vault))
        priority = watcher._determine_priority(docx_file)

        assert priority == "high"

    def test_xlsx_is_high_priority(self, temp_vault, temp_drop_folder):
        """XLSX files should be high priority."""
        xlsx_file = temp_drop_folder / "spreadsheet.xlsx"
        xlsx_file.write_bytes(b"fake xlsx")

        watcher = FileSystemWatcher(str(temp_vault))
        priority = watcher._determine_priority(xlsx_file)

        assert priority == "high"

    def test_txt_is_medium_priority(self, temp_vault, sample_text_file):
        """TXT files should be medium priority."""
        watcher = FileSystemWatcher(str(temp_vault))

        priority = watcher._determine_priority(sample_text_file)

        assert priority == "medium"

    def test_csv_is_medium_priority(self, temp_vault, temp_drop_folder):
        """CSV files should be medium priority."""
        csv_file = temp_drop_folder / "data.csv"
        csv_file.write_text("a,b,c")

        watcher = FileSystemWatcher(str(temp_vault))
        priority = watcher._determine_priority(csv_file)

        assert priority == "medium"

    def test_unknown_ext_is_low_priority(self, temp_vault, temp_drop_folder):
        """Unknown extensions should be low priority."""
        weird_file = temp_drop_folder / "file.xyz"
        weird_file.write_text("content")

        watcher = FileSystemWatcher(str(temp_vault))
        priority = watcher._determine_priority(weird_file)

        assert priority == "low"

    def test_urgent_keyword_is_high_priority(self, temp_vault, sample_urgent_file):
        """Files with 'urgent' in name should be high priority."""
        watcher = FileSystemWatcher(str(temp_vault))

        priority = watcher._determine_priority(sample_urgent_file)

        assert priority == "high"

    def test_invoice_keyword_is_high_priority(self, temp_vault, temp_drop_folder):
        """Files with 'invoice' in name should be high priority."""
        invoice_file = temp_drop_folder / "invoice_12345.txt"
        invoice_file.write_text("invoice content")

        watcher = FileSystemWatcher(str(temp_vault))
        priority = watcher._determine_priority(invoice_file)

        assert priority == "high"


# =============================================================================
# Tests: File Type Determination
# =============================================================================

class TestDetermineType:
    """Tests for _determine_type method."""

    def test_pdf_is_document(self, temp_vault, sample_pdf_file):
        """PDF should be categorized as document."""
        watcher = FileSystemWatcher(str(temp_vault))

        file_type = watcher._determine_type(sample_pdf_file)

        assert file_type == "document"

    def test_csv_is_data(self, temp_vault, temp_drop_folder):
        """CSV should be categorized as data."""
        csv_file = temp_drop_folder / "data.csv"
        csv_file.write_text("a,b")

        watcher = FileSystemWatcher(str(temp_vault))
        file_type = watcher._determine_type(csv_file)

        assert file_type == "data"

    def test_jpg_is_image(self, temp_vault, temp_drop_folder):
        """JPG should be categorized as image."""
        img_file = temp_drop_folder / "photo.jpg"
        img_file.write_bytes(b"fake image")

        watcher = FileSystemWatcher(str(temp_vault))
        file_type = watcher._determine_type(img_file)

        assert file_type == "image"

    def test_zip_is_archive(self, temp_vault, temp_drop_folder):
        """ZIP should be categorized as archive."""
        zip_file = temp_drop_folder / "archive.zip"
        zip_file.write_bytes(b"fake zip")

        watcher = FileSystemWatcher(str(temp_vault))
        file_type = watcher._determine_type(zip_file)

        assert file_type == "archive"

    def test_py_is_code(self, temp_vault, temp_drop_folder):
        """Python files should be categorized as code."""
        py_file = temp_drop_folder / "script.py"
        py_file.write_text("print('hello')")

        watcher = FileSystemWatcher(str(temp_vault))
        file_type = watcher._determine_type(py_file)

        assert file_type == "code"

    def test_unknown_is_other(self, temp_vault, temp_drop_folder):
        """Unknown extensions should be categorized as other."""
        weird_file = temp_drop_folder / "file.xyz"
        weird_file.write_text("content")

        watcher = FileSystemWatcher(str(temp_vault))
        file_type = watcher._determine_type(weird_file)

        assert file_type == "other"


# =============================================================================
# Tests: Size Formatting
# =============================================================================

class TestFormatSize:
    """Tests for _format_size method."""

    def test_bytes(self, temp_vault):
        """Small sizes should show in bytes."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher._format_size(500)

        assert "B" in result
        assert "500" in result

    def test_kilobytes(self, temp_vault):
        """Medium sizes should show in KB."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher._format_size(2048)

        assert "KB" in result

    def test_megabytes(self, temp_vault):
        """Large sizes should show in MB."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher._format_size(5 * 1024 * 1024)

        assert "MB" in result

    def test_gigabytes(self, temp_vault):
        """Very large sizes should show in GB."""
        watcher = FileSystemWatcher(str(temp_vault))

        result = watcher._format_size(3 * 1024 * 1024 * 1024)

        assert "GB" in result


# =============================================================================
# Tests: Logging
# =============================================================================

class TestLogging:
    """Tests for logging functionality."""

    def test_log_action_creates_daily_log(self, temp_vault):
        """log_action should create today's log file."""
        watcher = FileSystemWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test_action', {'key': 'value'})

        log_file = temp_vault / "Logs" / f"{today}.json"
        assert log_file.exists()

    def test_log_action_appends_to_existing(self, temp_vault, mock_log_file):
        """log_action should append to existing log file."""
        watcher = FileSystemWatcher(str(temp_vault))

        watcher.log_action('new_action', {'new': 'data'})

        logs = json.loads(mock_log_file.read_text())
        assert len(logs) == 2
        assert logs[1]['action_type'] == 'new_action'

    def test_log_action_includes_timestamp(self, temp_vault):
        """Log entries should include ISO timestamp."""
        watcher = FileSystemWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert 'timestamp' in logs[0]

    def test_log_action_includes_watcher_name(self, temp_vault):
        """Log entries should include watcher name."""
        watcher = FileSystemWatcher(str(temp_vault))
        today = datetime.now().strftime('%Y-%m-%d')

        watcher.log_action('test', {})

        log_file = temp_vault / "Logs" / f"{today}.json"
        logs = json.loads(log_file.read_text())
        assert logs[0]['watcher'] == 'FileSystemWatcher'


# =============================================================================
# Tests: Watcher Lifecycle
# =============================================================================

class TestWatcherLifecycle:
    """Tests for watcher start/stop lifecycle."""

    def test_stop_sets_is_running_false(self, temp_vault):
        """stop() should set is_running to False."""
        watcher = FileSystemWatcher(str(temp_vault))
        watcher.is_running = True

        watcher.stop()

        assert watcher.is_running is False

    def test_get_status_returns_dict(self, temp_vault):
        """get_status should return status dictionary."""
        watcher = FileSystemWatcher(str(temp_vault))

        status = watcher.get_status()

        assert isinstance(status, dict)
        assert 'name' in status
        assert 'is_running' in status
        assert status['name'] == 'FileSystemWatcher'


# =============================================================================
# Tests: DropFolderHandler
# =============================================================================

class TestDropFolderHandler:
    """Tests for DropFolderHandler event handler."""

    def test_on_created_ignores_directories(self, temp_vault):
        """on_created should ignore directory events."""
        watcher = FileSystemWatcher(str(temp_vault))
        handler = DropFolderHandler(watcher)

        # Create mock directory event
        mock_event = Mock()
        mock_event.is_directory = True

        # Should not raise or process
        handler.on_created(mock_event)

        # Verify no files were processed
        assert len(watcher.processed_files) == 0

    def test_on_created_processes_file(self, temp_vault, sample_text_file):
        """on_created should process file events."""
        watcher = FileSystemWatcher(str(temp_vault))
        handler = DropFolderHandler(watcher)

        # Create mock file event
        mock_event = Mock()
        mock_event.is_directory = False
        mock_event.src_path = str(sample_text_file)

        with patch.object(watcher, 'process_new_file') as mock_process:
            handler.on_created(mock_event)
            mock_process.assert_called_once()


# =============================================================================
# Run Tests
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
