"""
Human-in-the-Loop (HITL) Approval Workflow

This module provides the approval mechanism for sensitive actions.
Actions that require human approval are placed in Pending_Approval folder,
and only executed after being moved to Approved folder.

Usage:
    from src.utils.hitl import ApprovalManager

    manager = ApprovalManager('./AI_Employee_Vault')

    # Create approval request
    request_path = manager.create_approval_request(
        action_type='send_email',
        details={'to': 'client@example.com', 'subject': 'Invoice'},
        source_file='EMAIL_20260119_Invoice.md'
    )

    # Check if approved
    if manager.is_approved(request_path):
        # Execute action
        manager.mark_completed(request_path, success=True)
"""

import json
import shutil
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional, List
from enum import Enum
import logging


class ApprovalStatus(Enum):
    """Status of an approval request."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    COMPLETED = "completed"
    EXPIRED = "expired"


class ApprovalManager:
    """Manages human-in-the-loop approval workflow."""

    def __init__(self, vault_path: str):
        """
        Initialize ApprovalManager.

        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.pending_path = self.vault_path / 'Pending_Approval'
        self.approved_path = self.vault_path / 'Approved'
        self.rejected_path = self.vault_path / 'Rejected'
        self.done_path = self.vault_path / 'Done'
        self.logs_path = self.vault_path / 'Logs'

        # Ensure directories exist
        for path in [self.pending_path, self.approved_path, self.rejected_path,
                     self.done_path, self.logs_path]:
            path.mkdir(parents=True, exist_ok=True)

        self.logger = logging.getLogger('ApprovalManager')

    def create_approval_request(
        self,
        action_type: str,
        details: Dict[str, Any],
        source_file: Optional[str] = None,
        reason: str = "",
        urgency: str = "normal",
        expires_hours: int = 24,
        source_agent: Optional[str] = None,
        requires_local_action: bool = False,
        domain: Optional[str] = None,
    ) -> Path:
        """
        Create an approval request in Pending_Approval folder.

        Args:
            action_type: Type of action (send_email, payment, post_social, etc.)
            details: Dictionary with action details
            source_file: Original source file that triggered this action
            reason: Reason why approval is needed
            urgency: low, normal, high, critical
            expires_hours: Hours until request expires

        Returns:
            Path to the created approval request file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        expires_at = datetime.now().timestamp() + (expires_hours * 3600)

        # Determine approval reason if not provided
        if not reason:
            reason = self._get_default_reason(action_type, details)

        # Platinum Tier: agent tracking
        agent_line = f'\nsource_agent: "{source_agent}"' if source_agent else ''
        local_line = f'\nrequires_local_action: {str(requires_local_action).lower()}' if source_agent else ''

        content = f'''---
type: approval_request
action_type: "{action_type}"
source_file: "{source_file or 'manual'}"
created: "{datetime.now().isoformat()}"
expires_at: "{datetime.fromtimestamp(expires_at).isoformat()}"
urgency: "{urgency}"
status: pending{agent_line}{local_line}
---

# Approval Required: {action_type.replace('_', ' ').title()}

## Why Approval is Needed

{reason}

## Action Details

| Field | Value |
|-------|-------|
| **Type** | {action_type} |
| **Urgency** | {urgency.upper()} |
| **Source** | {source_file or 'Manual request'} |
| **Created** | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |
| **Expires** | {datetime.fromtimestamp(expires_at).strftime('%Y-%m-%d %H:%M:%S')} |

## Proposed Action

```json
{json.dumps(details, indent=2, default=str)}
```

{self._format_action_summary(action_type, details)}

## Approval Instructions

**To APPROVE this action:**
1. Review the details above carefully
2. Move this file to the `Approved` folder
3. The action will be executed automatically

**To REJECT this action:**
1. Move this file to the `Rejected` folder
2. Optionally add a note below explaining why

## Notes

<!-- Add any notes or modifications here -->

---

*This approval request was auto-generated by AI Employee.*
*Per Company Handbook rules, this action requires human approval.*
'''

        # Create approval file (supports domain subfolders for Platinum Tier)
        safe_type = action_type.replace(' ', '_')
        filename = f'{safe_type}_{timestamp}.md'
        if domain:
            target_dir = self.pending_path / domain
            target_dir.mkdir(parents=True, exist_ok=True)
            filepath = target_dir / filename
        else:
            filepath = self.pending_path / filename
        filepath.write_text(content, encoding='utf-8')

        self._log_action('approval_created', {
            'filepath': str(filepath),
            'action_type': action_type,
            'urgency': urgency
        })

        self.logger.info(f"Created approval request: {filepath}")
        return filepath

    def check_status(self, request_path: Path) -> ApprovalStatus:
        """
        Check the current status of an approval request.

        Args:
            request_path: Original path to the approval request

        Returns:
            Current ApprovalStatus
        """
        filename = request_path.name

        # Check each folder
        if (self.approved_path / filename).exists():
            return ApprovalStatus.APPROVED
        elif (self.rejected_path / filename).exists():
            return ApprovalStatus.REJECTED
        elif (self.done_path / filename).exists():
            return ApprovalStatus.COMPLETED
        elif (self.pending_path / filename).exists():
            # Check if expired
            content = (self.pending_path / filename).read_text()
            if self._is_expired(content):
                return ApprovalStatus.EXPIRED
            return ApprovalStatus.PENDING
        else:
            # File not found in any location
            return ApprovalStatus.EXPIRED

    def is_approved(self, request_path: Path) -> bool:
        """Check if a request has been approved."""
        return self.check_status(request_path) == ApprovalStatus.APPROVED

    def is_rejected(self, request_path: Path) -> bool:
        """Check if a request has been rejected."""
        return self.check_status(request_path) == ApprovalStatus.REJECTED

    def is_pending(self, request_path: Path) -> bool:
        """Check if a request is still pending."""
        return self.check_status(request_path) == ApprovalStatus.PENDING

    def get_approved_requests(self) -> List[Path]:
        """Get all approved requests waiting for execution."""
        return list(self.approved_path.glob('*.md'))

    def get_pending_requests(self) -> List[Path]:
        """Get all pending approval requests."""
        return list(self.pending_path.glob('*.md'))

    def mark_completed(
        self,
        request_path: Path,
        success: bool = True,
        result: Optional[str] = None
    ) -> None:
        """
        Mark an approved request as completed after execution.

        Args:
            request_path: Path to the approval request
            success: Whether the action succeeded
            result: Optional result message
        """
        filename = request_path.name

        # Find the file in Approved folder
        approved_file = self.approved_path / filename
        if not approved_file.exists():
            self.logger.warning(f"Approved file not found: {approved_file}")
            return

        # Read and update content
        content = approved_file.read_text()

        # Add completion note
        completion_note = f'''

---

## Execution Result

- **Status**: {'SUCCESS' if success else 'FAILED'}
- **Executed**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Result**: {result or 'Completed'}
'''
        content += completion_note

        # Move to Done folder
        done_file = self.done_path / filename
        done_file.write_text(content, encoding='utf-8')
        approved_file.unlink()

        self._log_action('approval_completed', {
            'filepath': str(done_file),
            'success': success,
            'result': result
        })

        self.logger.info(f"Marked as completed: {filename}")

    def expire_old_requests(self, hours: int = 24) -> List[Path]:
        """
        Move expired requests to Rejected folder.

        Args:
            hours: Expire requests older than this many hours

        Returns:
            List of expired request paths
        """
        expired = []

        for filepath in self.pending_path.glob('*.md'):
            content = filepath.read_text()
            if self._is_expired(content):
                # Move to rejected with expiration note
                content += f'\n\n---\n*Expired: {datetime.now().isoformat()}*\n'
                rejected_file = self.rejected_path / filepath.name
                rejected_file.write_text(content, encoding='utf-8')
                filepath.unlink()
                expired.append(rejected_file)

                self._log_action('approval_expired', {
                    'filepath': str(rejected_file)
                })

        return expired

    def _is_expired(self, content: str) -> bool:
        """Check if approval request content indicates expiration."""
        import re
        match = re.search(r'expires_at:\s*"([^"]+)"', content)
        if match:
            try:
                expires_at = datetime.fromisoformat(match.group(1))
                return datetime.now() > expires_at
            except:
                pass
        return False

    def _get_default_reason(self, action_type: str, details: Dict[str, Any]) -> str:
        """Get default reason based on action type."""
        reasons = {
            'send_email': "Email to external recipient requires review before sending.",
            'payment': f"Payment of ${details.get('amount', 'unknown')} requires authorization.",
            'post_social': "Social media post requires approval before publishing.",
            'delete_file': "File deletion is irreversible and requires confirmation.",
            'api_call': "External API call with side effects requires approval.",
            'contract': "Legal document requires human review.",
        }
        return reasons.get(action_type, "This action requires human approval per Company Handbook.")

    def _format_action_summary(self, action_type: str, details: Dict[str, Any]) -> str:
        """Format a human-readable summary of the action."""
        if action_type == 'send_email':
            return f'''
### Email Summary
- **To**: {details.get('to', 'N/A')}
- **Subject**: {details.get('subject', 'N/A')}
- **Preview**: {details.get('body', 'N/A')[:200]}...
'''
        elif action_type == 'payment':
            return f'''
### Payment Summary
- **Amount**: ${details.get('amount', 'N/A')}
- **Recipient**: {details.get('recipient', 'N/A')}
- **Method**: {details.get('method', 'N/A')}
- **Reference**: {details.get('reference', 'N/A')}
'''
        elif action_type == 'post_social':
            return f'''
### Social Media Post
- **Platform**: {details.get('platform', 'N/A')}
- **Content**: {details.get('content', 'N/A')[:280]}
'''
        return ""

    def _log_action(self, action_type: str, details: Dict[str, Any]) -> None:
        """Log an action to the daily log file."""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs_path / f'{today}.json'

        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'component': 'ApprovalManager',
            'action_type': action_type,
            'details': details
        }

        logs = []
        if log_file.exists():
            try:
                logs = json.loads(log_file.read_text())
            except:
                logs = []

        logs.append(log_entry)
        log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')


class ApprovalWatcher:
    """Watches for approved requests and triggers callbacks."""

    def __init__(self, vault_path: str, check_interval: int = 5):
        """
        Initialize ApprovalWatcher.

        Args:
            vault_path: Path to the Obsidian vault
            check_interval: Seconds between checks
        """
        self.manager = ApprovalManager(vault_path)
        self.check_interval = check_interval
        self.callbacks: Dict[str, callable] = {}
        self.is_running = False
        self.logger = logging.getLogger('ApprovalWatcher')

    def register_handler(self, action_type: str, callback: callable) -> None:
        """
        Register a callback for a specific action type.

        Args:
            action_type: Type of action to handle
            callback: Function to call when action is approved
                      Should accept (details: dict, filepath: Path) -> bool
        """
        self.callbacks[action_type] = callback
        self.logger.info(f"Registered handler for: {action_type}")

    def process_approved(self) -> int:
        """
        Process all approved requests.

        Returns:
            Number of requests processed
        """
        processed = 0

        for filepath in self.manager.get_approved_requests():
            try:
                # Parse the approval file
                content = filepath.read_text()
                action_type = self._extract_field(content, 'action_type')

                if action_type and action_type in self.callbacks:
                    # Extract details JSON
                    details = self._extract_json_details(content)

                    # Execute callback
                    try:
                        success = self.callbacks[action_type](details, filepath)
                        self.manager.mark_completed(filepath, success=success)
                        processed += 1
                    except Exception as e:
                        self.logger.error(f"Handler error for {action_type}: {e}")
                        self.manager.mark_completed(
                            filepath,
                            success=False,
                            result=f"Error: {str(e)}"
                        )
                else:
                    self.logger.warning(f"No handler for action type: {action_type}")

            except Exception as e:
                self.logger.error(f"Error processing {filepath}: {e}")

        return processed

    def _extract_field(self, content: str, field: str) -> Optional[str]:
        """Extract a field value from YAML frontmatter."""
        import re
        match = re.search(rf'{field}:\s*"([^"]+)"', content)
        return match.group(1) if match else None

    def _extract_json_details(self, content: str) -> Dict[str, Any]:
        """Extract JSON details block from content."""
        import re
        match = re.search(r'```json\n(.*?)\n```', content, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1))
            except:
                pass
        return {}

    def run(self) -> None:
        """Run the approval watcher loop."""
        import time

        self.logger.info("Starting ApprovalWatcher")
        self.is_running = True

        while self.is_running:
            try:
                # Process approved requests
                processed = self.process_approved()
                if processed:
                    self.logger.info(f"Processed {processed} approved requests")

                # Expire old requests
                expired = self.manager.expire_old_requests()
                if expired:
                    self.logger.info(f"Expired {len(expired)} old requests")

            except Exception as e:
                self.logger.error(f"Error in approval watcher: {e}")

            time.sleep(self.check_interval)

    def stop(self) -> None:
        """Stop the approval watcher."""
        self.is_running = False


# Convenience functions
def require_approval(
    vault_path: str,
    action_type: str,
    details: Dict[str, Any],
    **kwargs
) -> Path:
    """
    Create an approval request (convenience function).

    Args:
        vault_path: Path to vault
        action_type: Type of action
        details: Action details
        **kwargs: Additional arguments for create_approval_request

    Returns:
        Path to approval request
    """
    manager = ApprovalManager(vault_path)
    return manager.create_approval_request(action_type, details, **kwargs)


def check_approval(vault_path: str, request_path: Path) -> bool:
    """
    Check if a request is approved (convenience function).

    Args:
        vault_path: Path to vault
        request_path: Path to approval request

    Returns:
        True if approved
    """
    manager = ApprovalManager(vault_path)
    return manager.is_approved(request_path)
