"""Transaction log model for daily accounting summaries."""

from datetime import date, datetime, time
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field, computed_field


class TransactionEntry(BaseModel):
    """Individual transaction within a day."""
    time: time
    reference: str
    partner: str
    amount: Decimal
    transaction_type: str = Field(description="inbound or outbound")
    odoo_id: Optional[int] = None


class Transaction(BaseModel):
    """Daily transaction log for accounting activity."""

    # Date identifier
    log_date: date

    # Aggregated amounts
    total_inbound: Decimal = Field(ge=0, default=Decimal("0"))
    total_outbound: Decimal = Field(ge=0, default=Decimal("0"))

    # Transaction details
    inbound_transactions: list[TransactionEntry] = Field(default_factory=list)
    outbound_transactions: list[TransactionEntry] = Field(default_factory=list)

    # Sync metadata
    synced_at: datetime
    source: str = "odoo"

    @computed_field
    @property
    def net_change(self) -> Decimal:
        """Calculate net cash flow."""
        return self.total_inbound - self.total_outbound

    @computed_field
    @property
    def transaction_count(self) -> int:
        """Total number of transactions."""
        return len(self.inbound_transactions) + len(self.outbound_transactions)

    def add_inbound(self, entry: TransactionEntry) -> None:
        """Add an inbound transaction."""
        self.inbound_transactions.append(entry)
        self.total_inbound += entry.amount

    def add_outbound(self, entry: TransactionEntry) -> None:
        """Add an outbound transaction."""
        self.outbound_transactions.append(entry)
        self.total_outbound += entry.amount

    def to_markdown(self) -> str:
        """Convert transaction log to vault markdown format."""
        inbound_rows = "\n".join([
            f"| {t.time.strftime('%H:%M')} | {t.reference} | {t.partner} | ${t.amount:,.2f} |"
            for t in sorted(self.inbound_transactions, key=lambda x: x.time)
        ]) if self.inbound_transactions else "| - | No inbound transactions | - | - |"

        outbound_rows = "\n".join([
            f"| {t.time.strftime('%H:%M')} | {t.reference} | {t.partner} | ${t.amount:,.2f} |"
            for t in sorted(self.outbound_transactions, key=lambda x: x.time)
        ]) if self.outbound_transactions else "| - | No outbound transactions | - | - |"

        net_sign = "+" if self.net_change >= 0 else ""

        return f"""---
type: transaction_log
date: {self.log_date.isoformat()}
total_inbound: {self.total_inbound}
total_outbound: {self.total_outbound}
net_change: {self.net_change}
transaction_count: {self.transaction_count}
synced_at: {self.synced_at.isoformat()}
---

# Transaction Log: {self.log_date.isoformat()}

## Summary

| Metric | Amount |
|--------|--------|
| Total Inbound | ${self.total_inbound:,.2f} |
| Total Outbound | ${self.total_outbound:,.2f} |
| Net Change | {net_sign}${self.net_change:,.2f} |
| Transactions | {self.transaction_count} |

## Transactions

### Inbound

| Time | Reference | Partner | Amount |
|------|-----------|---------|--------|
{inbound_rows}

### Outbound

| Time | Reference | Partner | Amount |
|------|-----------|---------|--------|
{outbound_rows}

---

[Auto-generated by Odoo sync]
"""

    @property
    def vault_filename(self) -> str:
        """Generate vault filename for this transaction log."""
        return f"{self.log_date.isoformat()}.md"
